TASK_LANGFLOW_CHAT = "langflow_chat"
TASK_LANGFLOW_BATCH = "langflow_batch"
TASK_TRIAGE_ALERT = "triage_alert"
TASK_AUTONOMOUS_TASK = "autonomous_task"
TASK_ENRICH_ITEM = "enrich_item"
TASK_DIRECTORY_SYNC = "directory_sync"
TASK_MAXMIND_UPDATE = "maxmind_update"
TASK_REFRESH_BULK_SYNC_SCHEDULES = "refresh_bulk_sync_schedules"

WORKER_TASK_NAMES = (
    TASK_LANGFLOW_CHAT,
    TASK_LANGFLOW_BATCH,
    TASK_TRIAGE_ALERT,
    TASK_AUTONOMOUS_TASK,
    TASK_ENRICH_ITEM,
    TASK_DIRECTORY_SYNC,
    TASK_REFRESH_BULK_SYNC_SCHEDULES,
    TASK_MAXMIND_UPDATE,
)
