#!/usr/bin/env bash
# =============================================================================
# Tidemark Intercept — Quickstart Installer
# =============================================================================
# One-line install:
#   curl -fsSL https://go.tidemarksecurity.com/tmi | bash
#
# What this script does:
#   1. Creates a tidemark-intercept/ directory
#   2. Downloads docker-compose.yml
#   3. Generates .env with secure random credentials
#   4. Runs docker compose up -d
# =============================================================================
set -euo pipefail

# -- Config -------------------------------------------------------------------
REPO="tidemark-security/intercept"
BRANCH="main"
BASE_URL="https://raw.githubusercontent.com/${REPO}/${BRANCH}/docs/quickstart"
INSTALL_DIR="tidemark-intercept"

# -- Colors -------------------------------------------------------------------
if [[ -t 1 ]]; then
  RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
  BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
else
  RED=''; GREEN=''; YELLOW=''; BLUE=''; BOLD=''; NC=''
fi

# -- Helpers ------------------------------------------------------------------
info()  { echo -e "${BLUE}▸${NC} $*"; }
ok()    { echo -e "${GREEN}✓${NC} $*"; }
warn()  { echo -e "${YELLOW}⚠${NC} $*"; }
fail()  { echo -e "${RED}✗ $*${NC}" >&2; exit 1; }

generate_secret() {
  local len=${1:-32}
  # Try openssl first, fall back to /dev/urandom
  openssl rand -base64 48 2>/dev/null | tr -d '/+=' | head -c "$len" \
    || head -c 48 /dev/urandom | base64 | tr -d '/+=' | head -c "$len"
}

generate_fernet_key() {
  # Fernet requires exactly 32 bytes encoded as url-safe base64 (44 chars + padding)
  openssl rand 32 2>/dev/null | base64 | tr '+/' '-_' \
    || head -c 32 /dev/urandom | base64 | tr '+/' '-_'
}

# -- Preflight checks --------------------------------------------------------
check_deps() {
  command -v docker &>/dev/null || fail "Docker is not installed. See https://docs.docker.com/get-docker/"
  command -v curl   &>/dev/null || fail "curl is not installed."
  docker compose version &>/dev/null 2>&1 || fail "Docker Compose V2 is required. Update Docker or install the compose plugin."
}

# -- Main ---------------------------------------------------------------------
main() {
  echo ""
  echo -e "${BOLD}  Tidemark Intercept — Quickstart Installer${NC}"
  echo -e "  ──────────────────────────────────────────"
  echo ""

  check_deps

  # Create install directory
  if [[ -d "$INSTALL_DIR" ]]; then
    warn "Directory ${BOLD}${INSTALL_DIR}/${NC} already exists."
    if [[ -f "$INSTALL_DIR/.env" ]]; then
      info "Existing .env found — credentials will be preserved."
    fi
  else
    mkdir -p "$INSTALL_DIR"
    ok "Created ${BOLD}${INSTALL_DIR}/${NC}"
  fi

  cd "$INSTALL_DIR"

  # Download compose file (always fetch latest)
  info "Downloading docker-compose.yml …"
  curl -fsSL -o docker-compose.yml "${BASE_URL}/docker-compose.yml"
  ok "docker-compose.yml"

  # Generate .env if it doesn't exist
  if [[ ! -f .env ]]; then
    info "Generating secure credentials …"

    cat > .env <<EOF
# =============================================================================
# Tidemark Intercept — Instance Configuration
# =============================================================================
# Generated by the quickstart installer. Keep this file safe.
# To regenerate: delete this file and re-run the installer.
# =============================================================================

# --- Secrets (auto-generated) ------------------------------------------------
POSTGRES_PASSWORD=$(generate_secret 24)
LANGFLOW_DB_PASSWORD=$(generate_secret 24)
SECRET_KEY=$(generate_fernet_key)
MINIO_ROOT_USER=$(generate_secret 16)
MINIO_ROOT_PASSWORD=$(generate_secret 24)

# --- Langflow auth -----------------------------------------------------------
LANGFLOW_SUPERUSER=admin
LANGFLOW_SUPERUSER_PASSWORD=$(generate_secret 24)
LANGFLOW_SECRET_KEY=$(generate_secret 44)
LANGFLOW_API_KEY=$(generate_secret 44)

# --- Image version -----------------------------------------------------------
# TAG=0.1.0

# --- AI features (optional) --------------------------------------------------
# Add your OpenAI API key to enable AI/LLM features.
# Get one at https://platform.openai.com/api-keys
# OPENAI_API_KEY=
EOF

    ok "Generated .env with secure random credentials."
  else
    ok "Using existing .env (credentials preserved)."
  fi

  # Start it up
  echo ""
  info "Pulling latest images …"
  docker compose pull
  info "Starting Tidemark Intercept …"
  docker compose up -d --remove-orphans

  echo ""
  echo -e "${GREEN}  ┌──────────────────────────────────────────┐${NC}"
  echo -e "${GREEN}  │   Tidemark Intercept is starting up! 🚀  │${NC}"
  echo -e "${GREEN}  └──────────────────────────────────────────┘${NC}"
  echo ""
  echo "  Open:   http://localhost"
  echo "  Login:  admin / admin"
  echo ""
  echo "  Services:"
  echo "    Frontend UI ·····  http://localhost"
  echo "    Backend API ·····  http://localhost:8000"
  echo "    MinIO Console ···  http://localhost:9001"
  echo "    Langflow AI ·····  http://localhost:7860"
  echo ""
  echo -e "  ${YELLOW}Change the default admin password after first login.${NC}"
  echo ""
  echo -e "  To enable AI features, edit ${BOLD}${INSTALL_DIR}/.env${NC} and add your"
  echo -e "  OpenAI API key, then restart:  ${BLUE}docker compose restart${NC}"
  echo ""
  echo -e "  Then go to ${BOLD}Admin → Settings → Langflow → Open Wizard${NC}"
  echo -e "  to automatically configure Langflow."
  echo ""
}

main "$@"
